### ISSUE TITLE
I am having issues installing this.

### ISSUE THREAD

**Issue by alexmail34** [mkalygin/alfred-yandex-translate#1]
Hi, your workflow looks great but I am having a little trouble installing it. This is what I got in the terminal:

```
Alexandrs-MacBook-Pro:~ alex$ sudo npm install -g alfred-yandex-translate
Password:
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> alfred-yandex-translate@1.1.0 postinstall /usr/local/lib/node_modules/alfred-yandex-translate
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/alex/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-yandex-translate/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>

    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-yandex-translate/node_modules/execa/index.js:201:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/alex/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-yandex-translate/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-yandex-translate@1.1.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-yandex-translate@1.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-01-29T12_20_08_889Z-debug.log
Alexandrs-MacBook-Pro:~ alex$ 
```

I would greatly appreciate any help with installing this great workflow. 
Thank you in advance.

**Comment by mkalygin** [comment]
@alexmail34 hmmm... It must be `alfy` package issue. I think it's because you use `sudo`. Try `npm install -g alfred-yandex-translate` and you'll be good.

Check out this related issue: https://github.com/sindresorhus/alfred-emoj/issues/8.

Let me know if this helps.

**Comment by alexmail34** [comment]
Great! This did the trick :) 
Thank you for your time.
